### ISSUE TITLE
epic: decouple website from kernel

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer-technical-backlog#19]
To enable continuous delivery of different pieces of Decentraland Explorer, we consider that the components that make explorer work should have independent and decoupled delivery cycles. To do so, we already separated https://github.com/decentraland/unity-renderer and now we must separate the react app that makes the Website of https://play.decentraland.org.

It will not only enable independent releases, it will help Decentraland to be more Decentralized by itself. Reducing the entry barrier to create custom home-pages. And enabling anyone in the community to create their own https://mydomain/play to host their own Decentraland with their own customizations.

- [x] Create https://github.com/decentraland/explorer-website repository
- [x] Format code in website to prevent noise https://github.com/decentraland/explorer/pull/2480
- [x] Merge this PR https://github.com/decentraland/explorer/pull/2466
- [x] Create production CDN for `explorer-website` https://cdn.decentraland.org
- [x] Create testing CDN for `explorer-website` https://explorer-artifacts.decentraland.org
- [x] Connect `explorer-website` to testing cdn CDN
- [x] Define interface/[ACL](https://docs.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer) for kernel<>website interactions https://github.com/decentraland/kernel-interface/
- [x] Delegate into website the selection of Ethereum provider, not its name, the actual provider object
- [x] Enable custom renderer CDN and kernel CDN selection from website (query params `renderer` `renderer-branch` `kernel` and `kernel-branch` https://github.com/decentraland/explorer-website/pull/21)
- [x] Create server to embed /play in catalysts emulating CDN https://github.com/decentraland/play-server
- [x] Move into `explorer-website` logic to restore sessions and auto-login
- [x] Separate decentraland-ecs in its own repository, skip publishing https://github.com/decentraland/sdk/issues/1 https://github.com/decentraland/sdk/issues/4
- [x] `decentraland-ecs` now uses references to `@dcl/kernel` and `@dcl/unity-renderer`, not embeding artifacts
- [x] CLI gets adaptation code to use the new file structure https://github.com/decentraland/sdk/issues/12

QA
- [x] Log in with metamask should automatically login next time the page is refreshed
- [x] Preview mode must continue working
- [x] Login with guest works
- [x] Login with guest consistently uses the same guest until the session is expired
- [x] Login with metamask twice don't ask the user to sign the message both times if the previous session was not expired
- [x] Login with metamask, then guest, then metamask should not ask for signing message twice

Next steps, after merge:
- [x] Publish `build-ecs` and `amd` in new repository
- [x] Adapt preview.html to work with new programming model (WIP)
- [x] Move ECS to its own repo
- [x] Implement automatic rollouts
- [x] in SDK: kernel and unity-renderer should be dependencies of decentraland-ecs, stop embedding in `@/artifacts`
- [x] in CLI: make adaptation code to work with new folder structure. Make sure preview and export continue working.
- [ ] Configure Kernel feature flags from website (not blocker)
