### ISSUE TITLE
Kernel <> Renderer Protocol Anti-Corruption Layer

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer-technical-backlog#2]
## Problem Statement
Messaging protocol between Kernel and Renderer should be defined in an additional repository. This should enforce the contract between the two systems and prevent compatibility breaks on the future.

Currently, [this repository](https://github.com/decentraland/renderer-protocol/tree/main/src) was created to that effect.

### Actionables
To reach that state, the following is needed:

- [x] Create renderer-protocol repository
- [x] Make the repository build C# and typescript interfaces using a custom protobuf plugin
- [x] Implement proto definitions for the complete kernel<>renderer interface, grouped by system.
- [ ] Generate C# and TS code based on the protocol definitions
- [ ] On the `unity-renderer` side, bridge classes should not contain the `Controller` suffix anymore and match the `renderer-protocol` namespaces. This is partially implemented.
- [ ] On the `kernel` side, the new protocol structure should be implemented. Currently, all the messages are brought together in `UnityInterface` and `BrowserInterface`.
- [ ] Implement the new structure for renderer-side. Currently, all outgoing messages are brought together in `Interface.cs` file when they shouldn't.
- [ ] On kernel and renderer side, the CI should fail if the interfaces doesn't match the renderer-protocol definitions
- [ ] On kernel and renderer side, there should exist a mechanism to generate the interfaces of the renderer-protocol definitions
