### ISSUE TITLE
epic: pipelines with gradual rollouts for explorer, website, unity-renderer

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer-technical-backlog#20]
The pipeline would look like this:
1. Publish NPM package
2. Webhooks from NPM registry will trigger a pipeline to deploy the artifact as immutable url in a CDN
3. After it finishes, a rollout pipeline gets triggered, chaning the rollout percentage to 10%
4. If no new errors are found in the new deployment (rollbar + prometheus) increase to 50% after 1h
5. If new errors are found, reduce percentage to 0%
6. If no new errors are found in the new deployment (rollbar + prometheus) increase to 100% after 1h
7. If new errors are found, reduce percentage to 0%

Steps:
- [x] Define, document and implement mechanism to detect errors in deployments
- [x] Hook deployments of `@dcl/explorer-website` to https://cdn.decentraland.org
- [x] Hook deployments of `@dcl/kernel` to https://cdn.decentraland.org
- [x] Hook deployments of `@dcl/unity-renderer` to https://cdn.decentraland.org
- [x] Create a proper CDN uploader, to leverage cloudfront and to compress assets https://github.com/decentraland/cdn-uploader
- [x] Create a CDN mock that runs locally to debug and to embed in catalysts https://github.com/decentraland/play-server

Related tasks, intermediate steps:
- [x] https://github.com/decentraland/explorer/pull/2486
