### ISSUE TITLE
Fully integrate new plugin system architecture

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer-technical-backlog#25]
## Problem Statement
https://www.notion.so/decentraland/RFC-Plugin-pattern-for-Renderer-features-1e59c81336eb45d29ec78aa09f3ee063

## Actionables

- [x] Implement `PluginSystem` draft
- [ ] Implement `PluginSystem` as defined by [the proposal](https://www.notion.so/decentraland/RFC-Plugin-pattern-for-Renderer-features-1e59c81336eb45d29ec78aa09f3ee063)
- [ ] Refactor `DataStore` so it works as a modular service (stub?) locator.
- [ ] Refactor `Environment` so it works as a simpler service locator.
- [ ] Remove `HUDController` and replace it with the new `PluginSystem` design
- [ ] Convert all current features into plugins.
