### ISSUE TITLE
Extract Website from Explorer repository to its own repo

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer-technical-backlog#6]
## Problem Statement

Right now, [Explorer](https://github.com/decentraland/explorer/pulls) repository is the home of website and kernel.

In order to enable cross-platform support, each repository should be on charge of deploying a single package. 

Related ADRs:
* [ADR-25: Explorer Repositories Decoupling](https://github.com/decentraland/adr/blob/main/docs/ADR-25-explorer-repositories-decoupling-.md)
* [ADR-3: Explorer Packages Organization](https://github.com/decentraland/adr/blob/main/docs/ADR-3-explorer-packages-organization.md)

Explorer should only publish Kernel package. An additional website package should be published by its own repository.

### Actionables
- [x] Create another repository that publishes website package in its pipeline
- [x] Move website to another repository
- [ ] Re-wire explorer to work with external published website package
